##########-GENERAL-SETTINGS-##########
app_name: LLMS by Hand
app_version: 0.1.0
app_description: A simple application to create different LLM components by hand
debug: true
##########-DATA-SETTINGS-##########
data:
  verdict_url: https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/main/ch02/01_main-chapter-code/the-verdict.txt
  local_path: data

  